---
- name: Configure Master machine
  ansible.builtin.include_tasks: master.yml
  when: replication_role == 'master'

- name: Configure Standby
  ansible.builtin.include_tasks: standby.yml
  when: replication_role == 'standby'
